version: 2
updates:
- package-ecosystem: gomod
  directory: /acceptance-tests
  schedule:
    # Check for updates every weekday
    interval: "daily"
    time: "06:00"
    timezone: "Europe/Berlin"
  # Allow only 1 open pull requests for gomod to prevent parallel concourse runs
  open-pull-requests-limit: 1
  labels:
    - run-ci
- package-ecosystem: pip
  directory: /ci/scripts
  schedule:
    # Check for updates every weekday
    interval: "daily"
    time: "12:00"
    timezone: "Europe/Berlin"
  # Allow only 1 open pull requests for pip to prevent parallel concourse runs
  open-pull-requests-limit: 1
  labels:
    - run-ci
