haproxy/haproxy-3.2.9.tar.gz:
  size: 5123457
  object_id: 1bb7379a-82ab-40be-7f41-73f7311eb70e
  sha: sha256:e660d141b29019f4d198785b0834cc3e9c96efceeb807c2fff2fc935bd3354c2
haproxy/hatop-0.8.2:
  size: 74157
  object_id: 00125e3f-bdaa-4da3-583f-b680b0b30df4
  sha: sha256:6ba2136e98b9a436488be67a54a5295f55f38090157d09df0154dda493ac5815
haproxy/lua-5.4.8.tar.gz:
  size: 374332
  object_id: 11cb896a-5089-432c-7652-fb5504bd13ff
  sha: sha256:4f18ddae154e793e46eeab727c59ef1c0c0c2b744e7b94219710d76f530629ae
haproxy/pcre2-10.47.tar.gz:
  size: 2792969
  object_id: 37761873-8904-4a27-4b0c-df645dffd609
  sha: sha256:c08ae2388ef333e8403e670ad70c0a11f1eed021fd88308d7e02f596fcd9dc16
haproxy/socat-1.8.0.3.tar.gz:
  size: 744553
  object_id: 5a0cc86e-dd69-4089-73f7-cdf7297c1377
  sha: sha256:a9f9eb6cfb9aa6b1b4b8fe260edbac3f2c743f294db1e362b932eb3feca37ba4
keepalived/keepalived-2.3.4.tar.gz:
  size: 1241315
  object_id: 9fe43619-9129-4280-4e7c-b1750ea9a18e
  sha: sha256:6afd95ddb7d3e0d3b8b8e5b3a489144131b61a01b06d29e883d0c44acc8a36bf
