haproxy/haproxy-2.6.13.tar.gz:
  size: 4065839
  object_id: 33245725-79d4-4d26-6895-27fbf4813e7d
  sha: sha256:d69ff5233dbca657132ef280d111222ec1e33f5be1c1937d4e9ff516f63f5243
haproxy/hatop-0.8.2:
  size: 74157
  object_id: 00125e3f-bdaa-4da3-583f-b680b0b30df4
  sha: sha256:6ba2136e98b9a436488be67a54a5295f55f38090157d09df0154dda493ac5815
haproxy/lua-5.4.6.tar.gz:
  size: 363329
  object_id: 99682823-ff40-4d20-52d0-7728718a1668
  sha: sha256:7d5ea1b9cb6aa0b59ca3dde1c6adcb57ef83a1ba8e5432c0ecd06bf439b3ad88
haproxy/pcre2-10.42.tar.gz:
  size: 2397194
  object_id: 1411549b-cc2b-4140-68d1-f55bc6b17bef
  sha: sha256:c33b418e3b936ee3153de2c61cc638e7e4fe3156022a5c77d0711bcbb9d64f1f
haproxy/socat-1.7.4.4.tar.gz:
  size: 662968
  object_id: 674c1075-b8d9-4b29-5af3-d0d0ed1cbb09
  sha: sha256:0f8f4b9d5c60b8c53d17b60d79ababc4a0f51b3bb6d2bd3ae8a6a4b9d68f195e
keepalived/keepalived-2.2.8.tar.gz:
  size: 1202602
  object_id: 5f81963e-54cc-4faf-46cf-3c40cbb0924e
  sha: sha256:85882eb62974f395d4c631be990a41a839594a7e62fbfebcb5649a937a7a1bb6
