haproxy/haproxy-2.5.8.tar.gz:
  size: 3838130
  object_id: fd7defc3-6a29-4083-5046-fcaac9cd296f
  sha: sha256:8477167a4785757f35f478a584c9a0aadd77122a2acbe7276aafaa53b69b03ac
haproxy/hatop-0.8.2.tar.gz:
  size: 138030
  object_id: eca866ad-3c8f-4526-51d1-23179c1bbda8
  sha: sha256:99f9cd9ec1bc2bb8b84da276e670002fe993f5b26e65c15f65e40fdcb42616cb
haproxy/lua-5.4.4.tar.gz:
  size: 360876
  object_id: 5b2652c4-3c00-4d2d-742d-dda229e95bac
  sha: sha256:164c7849653b80ae67bec4b7473b884bf5cc8d2dca05653475ec2ed27b9ebf61
haproxy/pcre2-10.40.tar.gz:
  size: 2359622
  object_id: 3a0e0202-481e-4df9-63fe-7080a130223e
  sha: sha256:ded42661cab30ada2e72ebff9e725e745b4b16ce831993635136f2ef86177724
haproxy/socat-1.7.4.3.tar.gz:
  size: 655520
  object_id: 075f833c-03f8-48eb-555b-82a6befc2f2b
  sha: sha256:d697245144731423ddbbceacabbd29447089ea223e9a439b28f9ff90d0dd216e
keepalived/keepalived-2.2.7.tar.gz:
  size: 1180180
  object_id: 1045d407-50f8-4580-57de-3ef787a88b28
  sha: sha256:c61940d874154a560a54627ecf7ef47adebdf832164368d10bf242a4d9b7d49d
