haproxy/haproxy-3.2.11.tar.gz:
  size: 5129152
  object_id: 840cf84b-33ac-4f92-71a5-d996f68bf86c
  sha: sha256:1ded04101274ae686d11f55fb3874638e79bae4211e3e8caff95ef8b1b96a54b
haproxy/hatop-0.8.2:
  size: 74157
  object_id: 00125e3f-bdaa-4da3-583f-b680b0b30df4
  sha: sha256:6ba2136e98b9a436488be67a54a5295f55f38090157d09df0154dda493ac5815
haproxy/lua-5.4.8.tar.gz:
  size: 374332
  object_id: 11cb896a-5089-432c-7652-fb5504bd13ff
  sha: sha256:4f18ddae154e793e46eeab727c59ef1c0c0c2b744e7b94219710d76f530629ae
haproxy/pcre2-10.47.tar.gz:
  size: 2792969
  object_id: 37761873-8904-4a27-4b0c-df645dffd609
  sha: sha256:c08ae2388ef333e8403e670ad70c0a11f1eed021fd88308d7e02f596fcd9dc16
haproxy/socat-1.8.1.0.tar.gz:
  size: 766385
  object_id: 64d98e00-d156-43bb-6fa7-1e2c07cda727
  sha: sha256:9a884880b1b00dfb2ffc6959197b1554b200af731018174cd048115dc28ef239
keepalived/keepalived-2.3.4.tar.gz:
  size: 1241315
  object_id: 9fe43619-9129-4280-4e7c-b1750ea9a18e
  sha: sha256:6afd95ddb7d3e0d3b8b8e5b3a489144131b61a01b06d29e883d0c44acc8a36bf
