haproxy/haproxy-2.7.4.tar.gz:
  size: 4154182
  object_id: 909eae96-fd12-45eb-61c1-bc5eb869eadb
  sha: sha256:84cb806030569e866812eed38ebd1a8ea6fe1d9800001e59924ec3dd39553b9f
haproxy/hatop-0.8.2:
  size: 74157
  object_id: 00125e3f-bdaa-4da3-583f-b680b0b30df4
  sha: sha256:6ba2136e98b9a436488be67a54a5295f55f38090157d09df0154dda493ac5815
haproxy/lua-5.4.4.tar.gz:
  size: 360876
  object_id: a23b1602-be03-4bdf-485c-d72dcb81e3c2
  sha: sha256:164c7849653b80ae67bec4b7473b884bf5cc8d2dca05653475ec2ed27b9ebf61
haproxy/pcre2-10.42.tar.gz:
  size: 2397194
  object_id: 1411549b-cc2b-4140-68d1-f55bc6b17bef
  sha: sha256:c33b418e3b936ee3153de2c61cc638e7e4fe3156022a5c77d0711bcbb9d64f1f
haproxy/socat-1.7.4.4.tar.gz:
  size: 662968
  object_id: 674c1075-b8d9-4b29-5af3-d0d0ed1cbb09
  sha: sha256:0f8f4b9d5c60b8c53d17b60d79ababc4a0f51b3bb6d2bd3ae8a6a4b9d68f195e
keepalived/keepalived-2.2.7.tar.gz:
  size: 1180180
  object_id: c02487cf-d07c-4c46-576d-6ae6bb3ca51f
  sha: sha256:c61940d874154a560a54627ecf7ef47adebdf832164368d10bf242a4d9b7d49d
