haproxy/haproxy-2.6.7.tar.gz:
  size: 4028355
  object_id: 0889d657-c2c6-4c2d-4b3d-ba36bb16117d
  sha: sha256:cff9b8b18a52bfec277f9c1887fac93c18e1b9f3eff48892255a7c6e64528b7d
haproxy/hatop-0.8.2.tar.gz:
  size: 138030
  object_id: eca866ad-3c8f-4526-51d1-23179c1bbda8
  sha: sha256:99f9cd9ec1bc2bb8b84da276e670002fe993f5b26e65c15f65e40fdcb42616cb
haproxy/lua-5.4.4.tar.gz:
  size: 360876
  object_id: 5b2652c4-3c00-4d2d-742d-dda229e95bac
  sha: sha256:164c7849653b80ae67bec4b7473b884bf5cc8d2dca05653475ec2ed27b9ebf61
haproxy/pcre2-10.42.tar.gz:
  size: 2770528
  object_id: 5d942d98-c7a9-45de-789a-914c3016aa8c
  sha: sha256:a809c941600165d6917cccf637a1aea9d4902978321d6d4764f7c512b8387b31
haproxy/socat-1.7.4.4.tar.gz:
  size: 662968
  object_id: 964b0dcf-b063-44d3-5955-e439b103c7a2
  sha: sha256:0f8f4b9d5c60b8c53d17b60d79ababc4a0f51b3bb6d2bd3ae8a6a4b9d68f195e
keepalived/keepalived-2.2.7.tar.gz:
  size: 1180180
  object_id: 1045d407-50f8-4580-57de-3ef787a88b28
  sha: sha256:c61940d874154a560a54627ecf7ef47adebdf832164368d10bf242a4d9b7d49d
