haproxy/haproxy-2.5.4.tar.gz:
  size: 3819082
  object_id: 8b4e411e-1726-45ba-4d57-8f2a23df8d58
  sha: sha256:dc4015d85c7fef811b459803b763001d809b07a9251dc1864fedb9a07b44aefb
haproxy/hatop:
  size: 72445
  object_id: 17a5f66c-bbc1-4e4d-681c-e36420d3e0f5
  sha: sha256:a58450560686a429bfd6b3c8732f68f9043fa5ef2be5fac0218f48babfe57cbf
haproxy/lua-5.4.3.tar.gz:
  size: 358216
  object_id: 22238d40-0c0e-4bf2-7090-448b0ae68aa2
  sha: sha256:f8612276169e3bfcbcfb8f226195bfc6e466fe13042f1076cbde92b7ec96bbfb
haproxy/pcre2-10.37.tar.gz:
  size: 2299767
  object_id: 09f59432-df03-492a-479a-9cdfba50de19
  sha: sha256:04e214c0c40a97b8a5c2b4ae88a3aa8a93e6f2e45c6b3534ddac351f26548577
haproxy/socat-1.7.4.1.tar.gz:
  size: 648888
  object_id: f6492c7c-ccf1-4997-5e4b-10f97c0b1278
  sha: sha256:0c7e635070af1b9037fd96869fc45eacf9845cb54547681de9d885044538736d
keepalived/keepalived-2.2.2.tar.gz:
  size: 1159896
  object_id: e1cf2ca1-b248-4119-7dda-925e4271588f
  sha: sha256:103692bd5345a4ed9f4581632ea636214fdf53e45682e200aab122c4fa674ece
