haproxy/haproxy-1.8.13.tar.gz:
  size: 2063046
  object_id: bdaac0cd-4b13-4650-5237-d715b11dd3d9
  sha: 1c8588d63c7592404d0a3ea59aa41c2dccaaa909
haproxy/haproxy-1.8.17.tar.gz:
  size: 2077525
  object_id: 8fa8c082-2cb0-429a-5959-4a1d0d8c1759
  sha: 066878e2e443473d0cb9f8e74c28be822ec1e4be
haproxy/haproxy-1.8.20.tar.gz:
  size: 2083917
  object_id: 4a94da26-7a25-4117-5e48-057d6a31fa03
  sha: 7aa627e4ae0b2ee603d5525436c7f4d13b8e2f5e
haproxy/hatop:
  size: 72429
  sha: daddb3f13a70d4e2fa0802333c2e13468635171f
haproxy/lua-5.3.5.tar.gz:
  size: 303543
  object_id: 5acd4a28-51a4-45ed-536b-766fec394fa5
  sha: 112eb10ff04d1b4c9898e121d6bdf54a81482447
haproxy/pcre2-10.31.tar.gz:
  size: 2130574
  object_id: 7ae6656a-67f7-4376-4175-39d3b2400f4c
  sha: 7a77476a908c16cb26ad8a26363b67f00c8303bd
haproxy/socat-1.7.3.2.tar.gz:
  size: 615818
  object_id: 246271e3-bd49-4d1f-9410-c7002f44325c
  sha: a2446f65fb9fe9703b85ac5664c8920089fe32d8
keepalived/keepalived-1.2.24.tar.gz:
  size: 601873
  object_id: aa936bbe-fe82-49cc-82c8-99d867e5b4bb
  sha: a69b2c40627a9bd69698a57e81a8c8c97826025d
