haproxy/haproxy-2.2.14.tar.gz:
  size: 2923727
  object_id: 2639423c-b8b6-4c52-6fb4-b1ac779eea67
  sha: sha256:6a9b702f04b07786f3e5878de8172a727acfdfdbc1cefe1c7a438df372f2fb61
haproxy/hatop:
  size: 72445
  object_id: 17a5f66c-bbc1-4e4d-681c-e36420d3e0f5
  sha: sha256:a58450560686a429bfd6b3c8732f68f9043fa5ef2be5fac0218f48babfe57cbf
haproxy/lua-5.4.1.tar.gz:
  size: 353965
  object_id: bbdf988e-4504-49ea-5d88-49adb3488e96
  sha: 88961e7d4fda58ca2c6163938fd48db8880e803d
haproxy/pcre2-10.34.tar.gz:
  size: 2271533
  object_id: e803f1b2-9213-4238-4a7e-c5aa60c20b8c
  sha: 4393b5c912395c300ad921b76a4eb2bb109ddc0e
haproxy/socat-1.7.3.4.tar.gz:
  size: 615381
  object_id: 2afef81a-e6b6-4daf-6d4e-62db4c82b262
  sha: 2fa45073df61dd01b7ccbf2f8a8cc78580de7144
keepalived/keepalived-1.2.24.tar.gz:
  size: 601873
  object_id: aa936bbe-fe82-49cc-82c8-99d867e5b4bb
  sha: a69b2c40627a9bd69698a57e81a8c8c97826025d
