haproxy/haproxy-2.7.8.tar.gz:
  size: 4176647
  object_id: 41f3d1ad-081d-42da-7a2c-09dff8cd4736
  sha: sha256:15f2276971bbba8c47d86cc82ebfc6ec33e3aef2e4565058b2e4950c07b8e75c
haproxy/hatop-0.8.2:
  size: 74157
  object_id: 00125e3f-bdaa-4da3-583f-b680b0b30df4
  sha: sha256:6ba2136e98b9a436488be67a54a5295f55f38090157d09df0154dda493ac5815
haproxy/lua-5.4.5.tar.gz:
  size: 363316
  object_id: bf3a8555-990a-4da7-5ff8-de9a56f91db4
  sha: sha256:59df426a3d50ea535a460a452315c4c0d4e1121ba72ff0bdde58c2ef31d6f444
haproxy/pcre2-10.42.tar.gz:
  size: 2397194
  object_id: 1411549b-cc2b-4140-68d1-f55bc6b17bef
  sha: sha256:c33b418e3b936ee3153de2c61cc638e7e4fe3156022a5c77d0711bcbb9d64f1f
haproxy/socat-1.7.4.4.tar.gz:
  size: 662968
  object_id: 674c1075-b8d9-4b29-5af3-d0d0ed1cbb09
  sha: sha256:0f8f4b9d5c60b8c53d17b60d79ababc4a0f51b3bb6d2bd3ae8a6a4b9d68f195e
keepalived/keepalived-2.2.7.tar.gz:
  size: 1180180
  object_id: c02487cf-d07c-4c46-576d-6ae6bb3ca51f
  sha: sha256:c61940d874154a560a54627ecf7ef47adebdf832164368d10bf242a4d9b7d49d
