---
haproxy/pcre-8.36.tar.gz:
  object_id: bbbb840d-c7f5-4745-b4e3-c6b617069c02
  sha: fb537757756818133d8157ec878bc11f5a93ef4d
  size: 2009464
haproxy/haproxy-1.5.14.tar.gz:
  object_id: 46ad21b3-1fd0-4e9f-8ea5-80cc46e9f336
  sha: 159f5beb8fdc6b8059ae51b53dc935d91c0fb51f
  size: 1345345
ttar/ttar:
  object_id: 8876e372-2ece-4e29-bc9f-6f256d5e326b
  sha: 60bfdea4d0d50d5316ba1a9aca217f1d3f0ad1f5
  size: 567
haproxy/haproxy-1.6.10.tar.gz:
  object_id: 2bf5332a-f13d-40f7-b6c3-f32afa944275
  sha: 012f4caca3f39999e36229537798122c5f3698ac
  size: 1578385
