haproxy/haproxy-1.9.15.tar.gz:
  size: 2480346
  object_id: 4ed2fc61-5518-4cc8-765c-3d938c47c51b
  sha: 018876479d230ad50fe0564af9a5462f6aef5c3e
haproxy/hatop:
  size: 72429
  object_id: d86cd983-5ca3-4293-6620-56a9273be80f
  sha: daddb3f13a70d4e2fa0802333c2e13468635171f
haproxy/lua-5.3.5.tar.gz:
  size: 303543
  object_id: 5acd4a28-51a4-45ed-536b-766fec394fa5
  sha: 112eb10ff04d1b4c9898e121d6bdf54a81482447
haproxy/pcre2-10.34.tar.gz:
  size: 2271533
  sha: 4393b5c912395c300ad921b76a4eb2bb109ddc0e
haproxy/socat-1.7.3.4.tar.gz:
  size: 615381
  object_id: 2afef81a-e6b6-4daf-6d4e-62db4c82b262
  sha: 2fa45073df61dd01b7ccbf2f8a8cc78580de7144
keepalived/keepalived-1.2.24.tar.gz:
  size: 601873
  object_id: aa936bbe-fe82-49cc-82c8-99d867e5b4bb
  sha: a69b2c40627a9bd69698a57e81a8c8c97826025d
