haproxy/haproxy-2.8.10.tar.gz:
  size: 4392333
  object_id: 82d52729-5e18-41f1-4b3b-31f7de3e2a42
  sha: sha256:0d63cd46d9d10ac7dbc02f3c6769c1908f221e0a5c5b655a194655f7528d612a
haproxy/hatop-0.8.2:
  size: 74157
  object_id: 00125e3f-bdaa-4da3-583f-b680b0b30df4
  sha: sha256:6ba2136e98b9a436488be67a54a5295f55f38090157d09df0154dda493ac5815
haproxy/lua-5.4.7.tar.gz:
  size: 374097
  object_id: 6829cdad-976c-4cd5-765b-b8f4c106e268
  sha: sha256:9fbf5e28ef86c69858f6d3d34eccc32e911c1a28b4120ff3e84aaa70cfbf1e30
haproxy/pcre2-10.44.tar.gz:
  size: 2552792
  object_id: 7c730529-4f0e-4503-516b-8d7a46186f73
  sha: sha256:86b9cb0aa3bcb7994faa88018292bc704cdbb708e785f7c74352ff6ea7d3175b
haproxy/socat-1.8.0.1.tar.gz:
  size: 723747
  object_id: 844e5815-87e6-460a-7cd2-7fbd52d415c3
  sha: sha256:dc350411e03da657269e529c4d49fe23ba7b4610b0b225c020df4cf9b46e6982
keepalived/keepalived-2.3.1.tar.gz:
  size: 1210697
  object_id: a4e911bc-924f-4837-6760-87ecc1217ba0
  sha: sha256:92f4b69bfd998e2306d1995ad16fdad1b59e70be694c883385c5f55e02c62aa3
