haproxy/haproxy-3.2.12.tar.gz:
  size: 5130947
  object_id: 7db5ca5b-9831-4a18-4193-c454d2fcf3fe
  sha: sha256:310b424e60db2f3990206ca7c81293586842cb628e7dfad572c7146ae9e95a91
haproxy/hatop-0.8.2:
  size: 74157
  object_id: 00125e3f-bdaa-4da3-583f-b680b0b30df4
  sha: sha256:6ba2136e98b9a436488be67a54a5295f55f38090157d09df0154dda493ac5815
haproxy/lua-5.4.8.tar.gz:
  size: 374332
  object_id: 11cb896a-5089-432c-7652-fb5504bd13ff
  sha: sha256:4f18ddae154e793e46eeab727c59ef1c0c0c2b744e7b94219710d76f530629ae
haproxy/pcre2-10.47.tar.gz:
  size: 2792969
  object_id: 37761873-8904-4a27-4b0c-df645dffd609
  sha: sha256:c08ae2388ef333e8403e670ad70c0a11f1eed021fd88308d7e02f596fcd9dc16
haproxy/socat-1.8.1.1.tar.gz:
  size: 766524
  object_id: a3838efb-9096-4568-4d63-e148502758da
  sha: sha256:f68b602c80e94b4b7498d74ec408785536fe33534b39467977a82ab2f7f01ddb
keepalived/keepalived-2.3.4.tar.gz:
  size: 1241315
  object_id: 9fe43619-9129-4280-4e7c-b1750ea9a18e
  sha: sha256:6afd95ddb7d3e0d3b8b8e5b3a489144131b61a01b06d29e883d0c44acc8a36bf
