---
meta:
  name: haproxy
  target: sw
  url:     https://ci.vsphere.starkandwayne.com
  aws:
    bucket: cf-haproxy-boshrelease-pipeline # re-use old ci bucket after boshrelease rename
    access_key: (( vault "secret/aws/cfcommunity:access" ))
    secret_key: (( vault "secret/aws/cfcommunity:secret" ))
  github:
    owner: cloudfoundry-community
    repo:  haproxy-boshrelease
    private_key:  (( vault "secret/pipelines/haproxy-boshrelease/github:private" ))
    access_token: (( vault "secret/pipelines/haproxy-boshrelease/github:token" ))
  bosh-lite:
    target: https://10.58.111.46:25555
    deployment: haproxy-warden
  slack:
    webhook: (( vault "secret/pipelines/haproxy-boshrelease/slack:webhook" ))
    channel: "#haproxy-boshrelease"
